ci:
  skip: [
    perltidy,
  ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: perltidy
        name: perltidy
        description: Run the perltidy source code formatter on Perl source files
        entry: perltidy
        args: [
          --backup-and-modify-in-place,
          --backup-file-extension=/,
        ]
        language: perl
        types: [perl]

# vim:set ft=yaml ts=2 sw=2 et:
